# Generated by Django 2.2.6 on 2019-10-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191020_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='title',
            new_name='name',
        ),
    ]
