# Generated by Django 2.2.6 on 2019-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191020_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
